# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
         gradle-version: '8.4'

    # Grant execute permissions to gradlew script
    - name: Grant execute permissions
      run: chmod +x gradlew

    # Install Edge browser
    - name: Install Edge and EdgeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common apt-transport-https wget unzip
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
        EDGE_DRIVER_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE)
        wget https://msedgedriver.azureedge.net/${EDGE_DRIVER_VERSION}/edgedriver_linux64.zip -O edgedriver_linux64.zip
        unzip edgedriver_linux64.zip -d /usr/local/bin/
        rm edgedriver_linux64.zip
        sudo mv /usr/local/bin/msedgedriver /usr/local/bin/edgedriver

    #Verify edge version
    - name: Check Edge and EdgeDriver versions
      run: |
        microsoft-edge --version
        edgedriver --version

    # Run Gradle tests
    - name: Run Tests with Gradle
      run: ./gradlew test

    # Clear Gradle dependency cache
    - name: Clear dependency cache
      run: rm -rf ~/.gradle/caches


    # Install Gradle dependencies
    - name: Install dependencies
      run: ./gradlew dependencies


      # Run Gradle tests using the pre-built Docker image
    #- name: Run Tests with Gradle (Edge Docker)
     # run: docker pull selenium/edge-chromium:latest && docker run -d -p 4444:4444 selenium/edge-chromium:latest && ./gradlew test

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
